/// Synthetic test harness for order-book scenarios (§10.37).
///
/// Generates deterministic [`BookSnapshot`] and [`BookDelta`] messages and
/// drives them through one or more [`OrderBook`] instances.  Used in:
///
/// * **Stage 10.37** — scale (1 / 10 / 100 / 1000 symbols) and edge-case tests.
/// * **Stage 10.38** — property tests (bid < ask, no negative qty, monotonic seq).
/// * **Stage 10.39** — chaos tests (fault injection via the replay crate).
///
/// # Price convention
///
/// All synthetic prices are raw `i64` scaled integers representing
/// **units × 1000** (three implied decimal places).  Bids descend from
/// `MID_PRICE - TICK` downward; asks ascend from `MID_PRICE + TICK` upward.
/// This guarantees the bid side never crosses the ask side in normal scenarios.
use std::collections::HashMap;

use connector_core::{
    BookDelta, BookSnapshot, MarketType, MessageHeader, MessageType, PriceLevel, VenueId,
    SCHEMA_VERSION, TS_NONE, UPDATE_ID_NONE,
};

use crate::OrderBook;

// ---------------------------------------------------------------------------
// Price constants
// ---------------------------------------------------------------------------

/// Midpoint around which synthetic bid/ask levels are generated.
pub const MID_PRICE: i64 = 100_000;
/// Minimum price separation between adjacent synthetic levels.
pub const TICK_SIZE: i64 = 100;
/// Bid price used by `apply_wide_spread` — one tick above zero.
pub const WIDE_BID_PRICE: i64 = TICK_SIZE;
/// Ask price used by `apply_wide_spread` — far above the mid.
pub const WIDE_ASK_PRICE: i64 = 1_000_000_000;

// ---------------------------------------------------------------------------
// Xorshift64 PRNG (local copy — avoids a crate dependency for a tiny struct)
// ---------------------------------------------------------------------------

struct Prng {
    state: u64,
}

impl Prng {
    fn new(seed: u64) -> Self {
        Self {
            state: if seed == 0 {
                0xDEAD_BEEF_CAFE_F00D
            } else {
                seed
            },
        }
    }

    fn next(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.state = x;
        x
    }

    /// Positive quantity in [1, 1000].
    fn qty(&mut self) -> i64 {
        1 + (self.next() % 1_000) as i64
    }
}

// ---------------------------------------------------------------------------
// HarnessStats
// ---------------------------------------------------------------------------

/// Aggregate event counts for a [`SyntheticHarness`] session.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct HarnessStats {
    pub snapshots_applied: u64,
    pub deltas_applied: u64,
}

// ---------------------------------------------------------------------------
// InvariantViolation
// ---------------------------------------------------------------------------

/// A detected invariant violation in one of the harness's books.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InvariantViolation {
    /// `best_bid.price >= best_ask.price` — the book is crossed.
    BidAskCrossed {
        symbol: String,
        bid_price: i64,
        ask_price: i64,
    },
    /// A retained level has `qty <= 0` — the book stored an invalid entry.
    NonPositiveQty {
        symbol: String,
        side: &'static str,
        price: i64,
        qty: i64,
    },
}

/// Collection of invariant violations found by [`SyntheticHarness::check_invariants`].
#[derive(Debug, Default)]
pub struct InvariantViolations {
    pub violations: Vec<InvariantViolation>,
}

impl InvariantViolations {
    /// `true` when no violations were found.
    pub fn is_clean(&self) -> bool {
        self.violations.is_empty()
    }
    pub fn count(&self) -> usize {
        self.violations.len()
    }
}

// ---------------------------------------------------------------------------
// SyntheticHarness
// ---------------------------------------------------------------------------

/// Maintains a set of [`OrderBook`]s and drives them with deterministic
/// synthetic events.
///
/// All price and quantity values are generated by a seeded PRNG so replays
/// are fully reproducible.
pub struct SyntheticHarness {
    books: HashMap<String, OrderBook>,
    /// Monotonically increasing sequence number, used as `last_update_id`.
    seq: u64,
    prng: Prng,
    pub stats: HarnessStats,
}

impl SyntheticHarness {
    // ------------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------------

    /// Create an empty harness with no registered symbols.
    pub fn new(seed: u64) -> Self {
        Self {
            books: HashMap::new(),
            seq: 0,
            prng: Prng::new(seed),
            stats: HarnessStats::default(),
        }
    }

    /// Create a harness pre-populated with `n` synthetic symbols named
    /// `"SYM000001"`, `"SYM000002"`, … `"SYMnnnnnn"`.
    pub fn with_symbol_count(n: usize, seed: u64) -> Self {
        let mut h = Self::new(seed);
        h.add_symbol_count(n);
        h
    }

    /// Create a harness pre-populated with the given symbol names.
    pub fn with_symbols<S: Into<String>>(symbols: impl IntoIterator<Item = S>, seed: u64) -> Self {
        let mut h = Self::new(seed);
        for sym in symbols {
            h.add_symbol(sym);
        }
        h
    }

    // ------------------------------------------------------------------
    // Symbol registration
    // ------------------------------------------------------------------

    /// Register a single symbol.  No-op if already registered.
    pub fn add_symbol(&mut self, symbol: impl Into<String>) -> &mut Self {
        let s = symbol.into();
        self.books
            .entry(s.clone())
            .or_insert_with(|| OrderBook::new(s));
        self
    }

    /// Register `n` symbols named `"SYMnnnnnn"`.
    pub fn add_symbol_count(&mut self, n: usize) -> &mut Self {
        for i in 1..=n {
            self.add_symbol(format!("SYM{i:06}"));
        }
        self
    }

    // ------------------------------------------------------------------
    // Per-symbol event application
    // ------------------------------------------------------------------

    /// Apply a [`BookSnapshot`] with `bid_levels` bid levels and `ask_levels`
    /// ask levels.  Clears the existing book state.
    pub fn apply_snapshot_for(&mut self, symbol: &str, bid_levels: usize, ask_levels: usize) {
        let uid = self.next_seq();
        let bids = make_bid_levels(&mut self.prng, bid_levels);
        let asks = make_ask_levels(&mut self.prng, ask_levels);
        let snap = make_snapshot(symbol, uid, bids, asks);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_snapshot(&snap);
            self.stats.snapshots_applied += 1;
        }
    }

    /// Apply a [`BookDelta`] with `bid_levels` bid updates and `ask_levels` ask
    /// updates.  Prices are distinct from the current book so they always add
    /// new levels (not updates or removals).
    pub fn apply_delta_for(&mut self, symbol: &str, bid_levels: usize, ask_levels: usize) {
        let uid = self.next_seq();
        let bids = make_bid_levels(&mut self.prng, bid_levels);
        let asks = make_ask_levels(&mut self.prng, ask_levels);
        let d = make_delta(symbol, uid, bids, asks);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_delta(&d);
            self.stats.deltas_applied += 1;
        }
    }

    /// Apply a delta with **zero** bid and ask changes.
    ///
    /// `last_update_id` advances but no levels are added, modified, or removed.
    pub fn apply_zero_update(&mut self, symbol: &str) -> u64 {
        let uid = self.next_seq();
        let d = make_delta(symbol, uid, vec![], vec![]);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_delta(&d);
            self.stats.deltas_applied += 1;
        }
        uid
    }

    /// Replace the book with a snapshot where the bid is [`WIDE_BID_PRICE`]
    /// and the ask is [`WIDE_ASK_PRICE`] — the widest representable spread.
    pub fn apply_wide_spread(&mut self, symbol: &str) {
        let uid = self.next_seq();
        let bids = vec![PriceLevel {
            price: WIDE_BID_PRICE,
            qty: self.prng.qty(),
        }];
        let asks = vec![PriceLevel {
            price: WIDE_ASK_PRICE,
            qty: self.prng.qty(),
        }];
        let snap = make_snapshot(symbol, uid, bids, asks);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_snapshot(&snap);
            self.stats.snapshots_applied += 1;
        }
    }

    /// Replace the book with a snapshot that has **no bids** (asks only).
    pub fn apply_empty_bid_side(&mut self, symbol: &str) {
        let uid = self.next_seq();
        let asks = make_ask_levels(&mut self.prng, 5);
        let snap = make_snapshot(symbol, uid, vec![], asks);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_snapshot(&snap);
            self.stats.snapshots_applied += 1;
        }
    }

    /// Replace the book with a snapshot that has **no asks** (bids only).
    pub fn apply_empty_ask_side(&mut self, symbol: &str) {
        let uid = self.next_seq();
        let bids = make_bid_levels(&mut self.prng, 5);
        let snap = make_snapshot(symbol, uid, bids, vec![]);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_snapshot(&snap);
            self.stats.snapshots_applied += 1;
        }
    }

    /// Clear all levels by applying an empty snapshot (simulates delisting).
    ///
    /// After this call `book.is_empty()` is `true`.
    pub fn apply_delisting(&mut self, symbol: &str) {
        let uid = self.next_seq();
        let snap = make_snapshot(symbol, uid, vec![], vec![]);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_snapshot(&snap);
            self.stats.snapshots_applied += 1;
        }
    }

    /// Apply a single delta with `level_count` bid levels and `level_count` ask
    /// levels — exercises bulk insertion performance.
    pub fn apply_large_batch(&mut self, symbol: &str, level_count: usize) {
        let uid = self.next_seq();
        let bids = (0..level_count)
            .map(|i| PriceLevel {
                price: MID_PRICE - TICK_SIZE * (i as i64 + 1),
                qty: self.prng.qty(),
            })
            .collect();
        let asks = (0..level_count)
            .map(|i| PriceLevel {
                price: MID_PRICE + TICK_SIZE * (i as i64 + 1),
                qty: self.prng.qty(),
            })
            .collect();
        let snap = make_snapshot(symbol, uid, bids, asks);
        if let Some(book) = self.books.get_mut(symbol) {
            book.apply_snapshot(&snap);
            self.stats.snapshots_applied += 1;
        }
    }

    // ------------------------------------------------------------------
    // Broadcast — apply the same event to ALL symbols
    // ------------------------------------------------------------------

    /// Apply `apply_snapshot_for` to every registered symbol.
    ///
    /// Symbols are processed in sorted order to guarantee a deterministic
    /// PRNG sequence for a given seed.
    pub fn broadcast_snapshot(&mut self, bid_levels: usize, ask_levels: usize) {
        let mut symbols: Vec<String> = self.books.keys().cloned().collect();
        symbols.sort_unstable();
        for sym in symbols {
            self.apply_snapshot_for(&sym, bid_levels, ask_levels);
        }
    }

    /// Apply `apply_delta_for` to every registered symbol.
    ///
    /// Symbols are processed in sorted order to guarantee determinism.
    pub fn broadcast_delta(&mut self, bid_levels: usize, ask_levels: usize) {
        let mut symbols: Vec<String> = self.books.keys().cloned().collect();
        symbols.sort_unstable();
        for sym in symbols {
            self.apply_delta_for(&sym, bid_levels, ask_levels);
        }
    }

    /// Apply `apply_zero_update` to every registered symbol.
    ///
    /// Symbols are processed in sorted order to guarantee determinism.
    pub fn broadcast_zero_update(&mut self) {
        let mut symbols: Vec<String> = self.books.keys().cloned().collect();
        symbols.sort_unstable();
        for sym in symbols {
            self.apply_zero_update(&sym);
        }
    }

    // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------

    pub fn book(&self, symbol: &str) -> Option<&OrderBook> {
        self.books.get(symbol)
    }

    pub fn symbol_count(&self) -> usize {
        self.books.len()
    }

    pub fn current_seq(&self) -> u64 {
        self.seq
    }

    // ------------------------------------------------------------------
    // Invariant checking
    // ------------------------------------------------------------------

    /// Scan all books for invariant violations.
    ///
    /// Checks:
    /// 1. `best_bid.price < best_ask.price` when both sides are non-empty.
    /// 2. Every retained level has `qty > 0`.
    pub fn check_invariants(&self) -> InvariantViolations {
        let mut out = InvariantViolations::default();
        for (sym, book) in &self.books {
            // 1. Crossed book
            if let (Some(bb), Some(ba)) = (book.best_bid(), book.best_ask()) {
                if bb.price >= ba.price {
                    out.violations.push(InvariantViolation::BidAskCrossed {
                        symbol: sym.clone(),
                        bid_price: bb.price,
                        ask_price: ba.price,
                    });
                }
            }
            // 2. Non-positive quantities
            for lvl in book.bids() {
                if lvl.qty <= 0 {
                    out.violations.push(InvariantViolation::NonPositiveQty {
                        symbol: sym.clone(),
                        side: "bid",
                        price: lvl.price,
                        qty: lvl.qty,
                    });
                }
            }
            for lvl in book.asks() {
                if lvl.qty <= 0 {
                    out.violations.push(InvariantViolation::NonPositiveQty {
                        symbol: sym.clone(),
                        side: "ask",
                        price: lvl.price,
                        qty: lvl.qty,
                    });
                }
            }
        }
        out
    }

    // ------------------------------------------------------------------
    // Private helpers
    // ------------------------------------------------------------------

    fn next_seq(&mut self) -> u64 {
        self.seq += 1;
        self.seq
    }
}

// ---------------------------------------------------------------------------
// Free-function builders
// ---------------------------------------------------------------------------

fn make_header(msg_type: MessageType) -> MessageHeader {
    MessageHeader {
        schema_version: SCHEMA_VERSION,
        message_type: msg_type,
        venue_id: VenueId::BinanceSpot,
        market_type: MarketType::Spot,
        instrument_id: 0,
        connection_id: 0,
        instance_id: 0,
        sequence_number: 0,
        exchange_event_ts: TS_NONE,
        exchange_tx_ts: TS_NONE,
        local_recv_ts: TS_NONE,
        local_publish_ts: TS_NONE,
    }
}

fn make_bid_levels(prng: &mut Prng, count: usize) -> Vec<PriceLevel> {
    (0..count)
        .map(|i| PriceLevel {
            price: MID_PRICE - TICK_SIZE * (i as i64 + 1),
            qty: prng.qty(),
        })
        .collect()
}

fn make_ask_levels(prng: &mut Prng, count: usize) -> Vec<PriceLevel> {
    (0..count)
        .map(|i| PriceLevel {
            price: MID_PRICE + TICK_SIZE * (i as i64 + 1),
            qty: prng.qty(),
        })
        .collect()
}

fn make_snapshot(
    symbol: &str,
    uid: u64,
    bids: Vec<PriceLevel>,
    asks: Vec<PriceLevel>,
) -> BookSnapshot {
    BookSnapshot {
        header: make_header(MessageType::BookSnapshot),
        symbol: symbol.into(),
        price_scale: 2,
        qty_scale: 3,
        update_id: uid,
        bids,
        asks,
    }
}

fn make_delta(symbol: &str, uid: u64, bids: Vec<PriceLevel>, asks: Vec<PriceLevel>) -> BookDelta {
    BookDelta {
        header: make_header(MessageType::BookDelta),
        symbol: symbol.into(),
        price_scale: 2,
        qty_scale: 3,
        first_update_id: uid,
        final_update_id: uid,
        prev_update_id: UPDATE_ID_NONE,
        bids,
        asks,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // Scale: 1 symbol
    // -----------------------------------------------------------------------

    #[test]
    fn single_symbol_snapshot_then_deltas() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 1);

        h.apply_snapshot_for("BTCUSDT", 5, 5);
        for _ in 0..10 {
            h.apply_delta_for("BTCUSDT", 2, 2);
        }

        let book = h.book("BTCUSDT").unwrap();
        assert!(!book.is_empty());
        assert_eq!(h.stats.snapshots_applied, 1);
        assert_eq!(h.stats.deltas_applied, 10);
        assert!(h.check_invariants().is_clean());
    }

    #[test]
    fn single_symbol_sequence_is_monotonic() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 42);
        let mut last_uid = 0u64;

        h.apply_snapshot_for("BTCUSDT", 3, 3);
        let uid_after_snap = h.book("BTCUSDT").unwrap().last_update_id();
        assert!(uid_after_snap > last_uid);
        last_uid = uid_after_snap;

        for _ in 0..5 {
            h.apply_delta_for("BTCUSDT", 1, 1);
            let uid = h.book("BTCUSDT").unwrap().last_update_id();
            assert!(uid > last_uid, "uid must be strictly increasing");
            last_uid = uid;
        }
    }

    // -----------------------------------------------------------------------
    // Scale: 10 symbols
    // -----------------------------------------------------------------------

    #[test]
    fn ten_symbols_all_receive_updates() {
        let mut h = SyntheticHarness::with_symbol_count(10, 7);

        h.broadcast_snapshot(5, 5);
        for _ in 0..10 {
            h.broadcast_delta(2, 2);
        }

        assert_eq!(h.symbol_count(), 10);
        assert_eq!(h.stats.snapshots_applied, 10);
        assert_eq!(h.stats.deltas_applied, 100);

        for i in 1..=10usize {
            let sym = format!("SYM{i:06}");
            let book = h.book(&sym).unwrap();
            assert!(!book.is_empty(), "{sym} should not be empty");
        }
        assert!(h.check_invariants().is_clean());
    }

    #[test]
    fn ten_symbols_each_has_independent_last_update_id() {
        let mut h = SyntheticHarness::with_symbol_count(10, 8);
        h.broadcast_snapshot(2, 2);

        let uids: Vec<u64> = (1..=10usize)
            .map(|i| h.book(&format!("SYM{i:06}")).unwrap().last_update_id())
            .collect();

        // All update_ids are distinct since each gets its own seq tick.
        let mut sorted = uids.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 10, "all symbols must have unique update_ids");
    }

    // -----------------------------------------------------------------------
    // Scale: 100 symbols
    // -----------------------------------------------------------------------

    #[test]
    fn hundred_symbols_broadcast_delta_storm() {
        let mut h = SyntheticHarness::with_symbol_count(100, 99);

        h.broadcast_snapshot(10, 10);
        for _ in 0..20 {
            h.broadcast_delta(3, 3);
        }

        assert_eq!(h.stats.snapshots_applied, 100);
        assert_eq!(h.stats.deltas_applied, 2_000);
        assert!(
            h.check_invariants().is_clean(),
            "no invariant violations expected"
        );
    }

    #[test]
    fn hundred_symbols_zero_updates_leave_books_unchanged() {
        let mut h = SyntheticHarness::with_symbol_count(100, 100);

        h.broadcast_snapshot(5, 5);

        let depths_before: Vec<(usize, usize)> = (1..=100usize)
            .map(|i| {
                let b = h.book(&format!("SYM{i:06}")).unwrap();
                (b.bid_depth(), b.ask_depth())
            })
            .collect();

        // Zero updates don't change depths.
        h.broadcast_zero_update();

        let depths_after: Vec<(usize, usize)> = (1..=100usize)
            .map(|i| {
                let b = h.book(&format!("SYM{i:06}")).unwrap();
                (b.bid_depth(), b.ask_depth())
            })
            .collect();

        assert_eq!(depths_before, depths_after);
    }

    // -----------------------------------------------------------------------
    // Scale: 1000 symbols
    // -----------------------------------------------------------------------

    #[test]
    fn thousand_symbols_one_event_each_all_healthy() {
        let mut h = SyntheticHarness::with_symbol_count(1_000, 1234);
        h.broadcast_snapshot(5, 5);

        assert_eq!(h.symbol_count(), 1_000);
        assert_eq!(h.stats.snapshots_applied, 1_000);

        let v = h.check_invariants();
        assert!(v.is_clean(), "expected no violations, got {}", v.count());
    }

    #[test]
    fn thousand_symbols_snapshot_plus_delta_all_non_empty() {
        let mut h = SyntheticHarness::with_symbol_count(1_000, 5678);
        h.broadcast_snapshot(3, 3);
        h.broadcast_delta(2, 2);

        for i in 1..=1_000usize {
            let book = h.book(&format!("SYM{i:06}")).unwrap();
            assert!(!book.is_empty(), "SYM{i:06} must not be empty");
        }
        assert!(h.check_invariants().is_clean());
    }

    // -----------------------------------------------------------------------
    // Edge case: zero updates
    // -----------------------------------------------------------------------

    #[test]
    fn zero_update_advances_sequence_but_leaves_book_unchanged() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 1);

        h.apply_snapshot_for("BTCUSDT", 3, 3);
        let bid_depth_before = h.book("BTCUSDT").unwrap().bid_depth();
        let ask_depth_before = h.book("BTCUSDT").unwrap().ask_depth();
        let uid_before = h.book("BTCUSDT").unwrap().last_update_id();

        let new_uid = h.apply_zero_update("BTCUSDT");

        let book = h.book("BTCUSDT").unwrap();
        assert_eq!(
            book.bid_depth(),
            bid_depth_before,
            "zero update must not change bid depth"
        );
        assert_eq!(
            book.ask_depth(),
            ask_depth_before,
            "zero update must not change ask depth"
        );
        assert!(book.last_update_id() > uid_before, "update_id must advance");
        assert_eq!(
            book.last_update_id(),
            new_uid,
            "returned uid must match book"
        );
    }

    #[test]
    fn repeated_zero_updates_do_not_corrupt_book() {
        let mut h = SyntheticHarness::with_symbols(["ETHUSDT"], 2);

        h.apply_snapshot_for("ETHUSDT", 5, 5);
        for _ in 0..100 {
            h.apply_zero_update("ETHUSDT");
        }

        let book = h.book("ETHUSDT").unwrap();
        assert_eq!(book.bid_depth(), 5);
        assert_eq!(book.ask_depth(), 5);
        assert!(h.check_invariants().is_clean());
    }

    // -----------------------------------------------------------------------
    // Edge case: wide spreads
    // -----------------------------------------------------------------------

    #[test]
    fn wide_spread_both_sides_non_empty_bid_strictly_below_ask() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 3);
        h.apply_wide_spread("BTCUSDT");

        let book = h.book("BTCUSDT").unwrap();
        let bb = book.best_bid().expect("bid must be present");
        let ba = book.best_ask().expect("ask must be present");

        assert_eq!(bb.price, WIDE_BID_PRICE, "bid must be at WIDE_BID_PRICE");
        assert_eq!(ba.price, WIDE_ASK_PRICE, "ask must be at WIDE_ASK_PRICE");
        assert!(
            bb.price < ba.price,
            "bid must be strictly below ask even for wide spreads"
        );
        assert!(h.check_invariants().is_clean());
    }

    #[test]
    fn wide_spread_quantifies_the_gap() {
        let mut h = SyntheticHarness::with_symbols(["SOLUSDT"], 4);
        h.apply_wide_spread("SOLUSDT");

        let book = h.book("SOLUSDT").unwrap();
        let spread = book.best_ask().unwrap().price - book.best_bid().unwrap().price;
        assert!(spread > 1_000, "spread should be very wide, got {spread}");
    }

    // -----------------------------------------------------------------------
    // Edge case: empty bid side
    // -----------------------------------------------------------------------

    #[test]
    fn empty_bid_side_best_bid_is_none() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 5);
        h.apply_empty_bid_side("BTCUSDT");

        let book = h.book("BTCUSDT").unwrap();
        assert!(book.best_bid().is_none(), "bid side must be empty");
        assert!(book.best_ask().is_some(), "ask side must have levels");
        assert_eq!(book.bid_depth(), 0);
        assert!(book.ask_depth() > 0);
    }

    #[test]
    fn empty_bid_side_does_not_trigger_invariant_violation() {
        // An empty bid side is valid — one-sided book is not a crossed book.
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 6);
        h.apply_empty_bid_side("BTCUSDT");
        assert!(h.check_invariants().is_clean());
    }

    // -----------------------------------------------------------------------
    // Edge case: empty ask side
    // -----------------------------------------------------------------------

    #[test]
    fn empty_ask_side_best_ask_is_none() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 7);
        h.apply_empty_ask_side("BTCUSDT");

        let book = h.book("BTCUSDT").unwrap();
        assert!(book.best_ask().is_none(), "ask side must be empty");
        assert!(book.best_bid().is_some(), "bid side must have levels");
    }

    #[test]
    fn empty_ask_side_does_not_trigger_invariant_violation() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 8);
        h.apply_empty_ask_side("BTCUSDT");
        assert!(h.check_invariants().is_clean());
    }

    // -----------------------------------------------------------------------
    // Edge case: delisting
    // -----------------------------------------------------------------------

    #[test]
    fn delisting_clears_all_levels() {
        let mut h = SyntheticHarness::with_symbols(["BNBUSDT"], 9);

        h.apply_snapshot_for("BNBUSDT", 10, 10);
        assert!(!h.book("BNBUSDT").unwrap().is_empty());

        h.apply_delisting("BNBUSDT");

        let book = h.book("BNBUSDT").unwrap();
        assert!(book.is_empty(), "delisted book must be empty");
        assert_eq!(book.bid_depth(), 0);
        assert_eq!(book.ask_depth(), 0);
        assert!(book.best_bid().is_none());
        assert!(book.best_ask().is_none());
    }

    #[test]
    fn delisting_advances_update_id() {
        let mut h = SyntheticHarness::with_symbols(["BNBUSDT"], 10);

        h.apply_snapshot_for("BNBUSDT", 3, 3);
        let uid_before = h.book("BNBUSDT").unwrap().last_update_id();

        h.apply_delisting("BNBUSDT");
        let uid_after = h.book("BNBUSDT").unwrap().last_update_id();

        assert!(uid_after > uid_before, "delisting must advance update_id");
    }

    #[test]
    fn relist_after_delisting_works() {
        let mut h = SyntheticHarness::with_symbols(["XRPUSDT"], 11);

        h.apply_snapshot_for("XRPUSDT", 5, 5);
        h.apply_delisting("XRPUSDT");
        assert!(h.book("XRPUSDT").unwrap().is_empty());

        h.apply_snapshot_for("XRPUSDT", 3, 3);
        let book = h.book("XRPUSDT").unwrap();
        assert!(
            !book.is_empty(),
            "book should be non-empty after re-listing"
        );
        assert!(h.check_invariants().is_clean());
    }

    // -----------------------------------------------------------------------
    // Edge case: large batch updates
    // -----------------------------------------------------------------------

    #[test]
    fn large_batch_update_ten_thousand_levels() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 12);
        h.apply_large_batch("BTCUSDT", 10_000);

        let book = h.book("BTCUSDT").unwrap();
        assert_eq!(book.bid_depth(), 10_000, "must have 10k bid levels");
        assert_eq!(book.ask_depth(), 10_000, "must have 10k ask levels");
        assert!(h.check_invariants().is_clean());
    }

    #[test]
    fn large_batch_best_bid_and_ask_are_correct() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 13);
        h.apply_large_batch("BTCUSDT", 100);

        let book = h.book("BTCUSDT").unwrap();
        // Best bid = highest bid price = MID_PRICE - TICK_SIZE (closest to mid).
        assert_eq!(book.best_bid().unwrap().price, MID_PRICE - TICK_SIZE);
        // Best ask = lowest ask price = MID_PRICE + TICK_SIZE.
        assert_eq!(book.best_ask().unwrap().price, MID_PRICE + TICK_SIZE);
    }

    #[test]
    fn large_batch_then_delisting_leaves_empty_book() {
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 14);
        h.apply_large_batch("BTCUSDT", 5_000);
        h.apply_delisting("BTCUSDT");
        assert!(h.book("BTCUSDT").unwrap().is_empty());
    }

    // -----------------------------------------------------------------------
    // Invariant checker: detects violations
    // -----------------------------------------------------------------------

    #[test]
    fn invariant_check_clean_after_normal_scenarios() {
        let mut h = SyntheticHarness::with_symbol_count(5, 99);

        h.broadcast_snapshot(5, 5);
        h.broadcast_delta(2, 2);
        h.apply_zero_update("SYM000001");
        h.apply_wide_spread("SYM000002");
        h.apply_empty_bid_side("SYM000003");
        h.apply_empty_ask_side("SYM000004");
        h.apply_large_batch("SYM000005", 500);

        assert!(
            h.check_invariants().is_clean(),
            "all normal scenarios must be clean"
        );
    }

    #[test]
    fn invariant_check_detects_crossed_book_from_direct_snapshot() {
        // Construct a crossed book by providing a snapshot where bid > ask.
        // The OrderBook stores what it's told; the invariant checker catches it.
        let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 77);

        // Feed a crossed snapshot directly (bid price > ask price).
        let uid = h.next_seq();
        let snap = make_snapshot(
            "BTCUSDT",
            uid,
            vec![PriceLevel { price: 200, qty: 1 }], // bid = 200
            vec![PriceLevel { price: 100, qty: 1 }], // ask = 100  ← crossed
        );
        h.books.get_mut("BTCUSDT").unwrap().apply_snapshot(&snap);
        h.stats.snapshots_applied += 1;

        let v = h.check_invariants();
        assert!(!v.is_clean(), "crossed book must be detected");
        assert_eq!(v.count(), 1);
        assert!(matches!(
            &v.violations[0],
            InvariantViolation::BidAskCrossed {
                bid_price: 200,
                ask_price: 100,
                ..
            }
        ));
    }

    #[test]
    fn invariant_check_finds_multiple_violations_across_symbols() {
        let mut h = SyntheticHarness::with_symbol_count(3, 88);

        // Set up two crossed books.
        for sym in ["SYM000001", "SYM000002"] {
            let uid = h.next_seq();
            let snap = make_snapshot(
                sym,
                uid,
                vec![PriceLevel { price: 500, qty: 1 }],
                vec![PriceLevel { price: 100, qty: 1 }],
            );
            h.books.get_mut(sym).unwrap().apply_snapshot(&snap);
            h.stats.snapshots_applied += 1;
        }

        // SYM000003 is fine.
        h.apply_snapshot_for("SYM000003", 3, 3);

        let v = h.check_invariants();
        assert_eq!(v.count(), 2, "expected exactly 2 crossed-book violations");
    }

    // -----------------------------------------------------------------------
    // HarnessStats
    // -----------------------------------------------------------------------

    #[test]
    fn stats_count_snapshots_and_deltas() {
        let mut h = SyntheticHarness::with_symbols(["A", "B"], 1);
        h.apply_snapshot_for("A", 2, 2);
        h.apply_snapshot_for("B", 2, 2);
        h.apply_delta_for("A", 1, 1);
        h.apply_delta_for("A", 1, 1);
        h.apply_delta_for("B", 1, 1);

        assert_eq!(h.stats.snapshots_applied, 2);
        assert_eq!(h.stats.deltas_applied, 3);
    }

    #[test]
    fn broadcast_counts_all_symbols() {
        let mut h = SyntheticHarness::with_symbol_count(7, 2);
        h.broadcast_snapshot(1, 1);
        h.broadcast_delta(1, 1);
        assert_eq!(h.stats.snapshots_applied, 7);
        assert_eq!(h.stats.deltas_applied, 7);
    }

    // -----------------------------------------------------------------------
    // Determinism
    // -----------------------------------------------------------------------

    #[test]
    fn same_seed_produces_same_book_checksums() {
        let run = |seed: u64| {
            let mut h = SyntheticHarness::with_symbol_count(5, seed);
            h.broadcast_snapshot(5, 5);
            h.broadcast_delta(3, 3);
            (1..=5usize)
                .map(|i| h.book(&format!("SYM{i:06}")).unwrap().checksum())
                .collect::<Vec<_>>()
        };

        assert_eq!(
            run(42),
            run(42),
            "same seed must produce identical book states"
        );
    }

    #[test]
    fn different_seeds_produce_different_quantities() {
        let checksums_a: Vec<u64> = {
            let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 1);
            h.apply_snapshot_for("BTCUSDT", 5, 5);
            vec![h.book("BTCUSDT").unwrap().checksum()]
        };
        let checksums_b: Vec<u64> = {
            let mut h = SyntheticHarness::with_symbols(["BTCUSDT"], 2);
            h.apply_snapshot_for("BTCUSDT", 5, 5);
            vec![h.book("BTCUSDT").unwrap().checksum()]
        };
        assert_ne!(
            checksums_a, checksums_b,
            "different seeds should produce different quantities"
        );
    }
}
